version: '3'
services:
    #PHP Service
    codepractice-fe:
        image: node:latest
        container_name: codepractice-fe
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: codepractice-fe
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - codepractice-fe-network

    #Nginx Service
    webserver-codepractice:
        image: nginx:alpine
        container_name: webserver-codepractice
        restart: unless-stopped
        tty: true
        ports:
            - '2000:80'
            - '2443:443'
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - codepractice-fe-network

#Docker Networks
networks:
    codepractice-fe-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
