version: '3'
services:
    #PHP Service
    codepractice-fe:
        image: node:latest
        container_name: codepractice-fe
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: codepractice-fe
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www

    #Nginx Service
    webserver-codepractice-fe:
        image: nginx:alpine
        container_name: webserver-codepractice-fe
        restart: unless-stopped
        tty: true
        ports:
            - '2000:80'
            - '2443:443'
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/

#Docker Networks
#Volumes
volumes:
    dbdata:
      driver: local
